version: "3.3"

services:

  postgresdb:
    build:
      context: ./docker
      dockerfile: postgres.dockerfile
    volumes:
      - delfin-database-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresdb
    env_file:
      - .env.local
    ports:
      - "5050:80"

volumes:
  delfin-database-data:
  pgadmin-data: